### ISSUE TITLE
Detect over which connected grid an item is being dragged

### ISSUE THREAD

**Issue by awreccan** [haltu/muuri#109]
Suppose we have multiple [connected grids](https://github.com/haltu/muuri#dragsort-). When I drag an item from one of the grids, it creates a "placeholder gap" in whichever grid will receive the item if the item is dropped. 

- Is there an API to get that grid? 
- If not, can we have one please?
  - While such an API doesn't exist, is there any "hack" to get the grid with the "placeholder gap"?

**Comment by niklasramo** [comment]
About that last point, Muuri actually _does_ check if an item is visually over a grid, but it's all internal stuff. If need arises, it could be refactored to trigger an event. However, it's a bit more complicated than that and there are some performance issues to watch out for.

**Comment by awreccan** [comment]
Can't believe I missed those events! But just for clarity, could you
confirm that the following points are correct?

   - When you say *visually *over a grid, you mean the intersection area
   between the dragged item and the compared item is between 0 and the
threshold/tolerance
   provided by dragSortPredicate
   <https://github.com/haltu/muuri#dragsortpredicate->, and there's no
   event for that.
   - send <https://github.com/haltu/muuri#send>/receive
   <https://github.com/haltu/muuri#receive>/beforeSend
   <https://github.com/haltu/muuri#beforesend>/beforeReceive
   <https://github.com/haltu/muuri#beforereceive> are events that tell us
   that the "placeholder gap" has changed (or as you say, the item has been
   moved, even though the drag is still underway.)

**Comment by awreccan** [comment]
Can't believe I missed those events! But just for clarity, could you confirm that the following points are correct?

- When you say visually over a grid, you mean the intersection area between the dragged item and the compared item is between 0 and the [threshold/tolerance provided by dragSortPredicate](https://github.com/haltu/muuri#dragsortpredicate-), and there's no event for that.
- send/receive/beforeSend/beforeReceive are events that tell us that the "placeholder gap" has changed (or as you say, the item has been moved, even though the drag is still underway.)

**Comment by niklasramo** [comment]
> When you say visually over a grid, you mean the intersection area between the dragged item and the compared item is between 0 and the threshold/tolerance provided by dragSortPredicate, and there's no event for that.

Yep, that's part of the story and also correct.

More specifically, when you drag an item Muuri internally checks if the item overlaps any of the connected containers (including it's own current container if so specified) enough to satisfy the dragSortPredicate's threshold. This is a performance optimization so we would not need to compare the item to every other item in all the connected grids. When/if the first suitable container is found, Muuri proceeds to check which item it overlaps the most inside that container, and if that item satisfies the threshold.

This procedure can be pretty heavy depending on the amount of items, and it is triggered on every drag move. That's why Muuri has dragSortInterval option to add a little headroom there so that the heavy calculations can be debounced.

> send/receive/beforeSend/beforeReceive are events that tell us that the "placeholder gap" has changed (or as you say, the item has been moved, even though the drag is still underway.)

Yep, exactly.

**Comment by awreccan** [comment]
Thanks!
