### ISSUE TITLE
muuri + bootstrap: items in grid overlapping on load

### ISSUE THREAD

**Issue by mmikaela** [haltu/muuri#111]
Hi,
I'm a student getting my feet wet with code, so let me know if my explanation or JSFiddle doesn't make sense.

I tried to combine Muuri with the Bootstrap framework, since I wasn't sure how else to specify different sizes for different items with Muuri alone. I ran into the issue mentioned in #59, and used some HTML/CSS fixes without knowing the solution from that post and #70. 

During and after the process of fixing that, I noticed launching or reloading the page causes the grid items to pile on top of each other randomly instead of adhering to the grid. With every reload, the overlapping is different each time. 

If I change my browser window from full screen to a different size, or vice versa, it's fixed.  Unfortunately, using a javascript command that resizes the window isn't an option since that will affect the experience of people who usually browse in full screen. 

From what I can tell, it seems like the overlapping isn't caused by anything I wrote, but I could be wrong. My fixes for the percentage issue also may be affecting it, since I didn't change layout.rounding to false. I'm just really confused why my code needs the browser window to be resized before it interprets the code properly.

[My fiddle](https://jsfiddle.net/6ogofc14/4/)
(I couldn't figure out how to source bootstrap or Muuri into this fiddle, so you will probably have to copy the provided HTML, CSS, and JS into your own code editor and source Bootstrap and Muuri to see what I'm talking about. Sorry!)

(PS: I'm also aware my grid awkwardly pushes some items down if the aspect ratio of the browser changes, but that's a different issue that's easier to fix)

**Comment by niklasramo** [comment]
You are using images inside the items, so you _at least_ need to call `.refreshItems()` after the images have loaded.

**Comment by mmikaela** [comment]
I wasn't exactly sure how to add .refreshItems (even after looking at the **grid.refreshItems( [items] )** section in the instructions), but I used `document.onload.grid.refreshItems();` in my script tags after the grid variable. It helped for the most part, but it still happens. The overlapping isn't as extreme, and/or it doesn't happen consistently upon every refresh.

I put up everything [temporarily on a server](http://people.vcu.edu/~mattesmj/bugtesting/browse.html) to help you see what I mean and have a closer look at the code. I also have a [screenshot here](http://people.vcu.edu/~mattesmj/bugtesting/Screen%20Shot%202017-11-15%20at%203.01.04%20PM.png) showing it in the bottom right corner.

**Comment by dgeorgy007** [comment]
I am using React and I am also getting a random overlapping issue happening.
I use img tags inside divs.  To be more precise the image actually completely hides the other image which has been dragged over it.

I've tried calling refreshItems on window.setTimeout of 2secs - to ensure the images have finished loading.  But I don't know if this is the same issue as the above.

**Comment by niklasramo** [comment]
If you use images inside the items and the images affect the items' dimensions you need to do this (at minimum):

```
var grid = new Muuri('.grid');
window.addEventListener('load', function () {
  grid.refreshItems().layout();
});
``` 

`window`'s load event is called after all images have been loaded. Using `setTimeout` is risky, because you really can't use it to detect when all images have loaded, it _might_ work sometimes.

Here's an old related issue: https://github.com/haltu/muuri/issues/34. Muuri's API has changed from those times though, but the logic is pretty much the same.

**Comment by niklasramo** [comment]
I really ought to write a paragraph to the docs about dealing with images and links inside the items, because these issues keep popping up.

**Comment by dgeorgy007** [comment]
I'm calculating the height and width of the items explicitly based on the
image dimensions which are stored in the db.

Isn't this different to the scenario you mentioned?


On 21/11/2017 10:27 PM, "Niklas Rämö" <notifications@github.com> wrote:

If you use images inside the items and the images affect the items'
dimensions you need to do this (at minimum):

var grid = new Muuri('.grid');
window.addEventListener('load', function () {
  grid.refreshItems().layout();
});

window's load event is called after all images have been loaded. Using
setTimeout is risky, because you really can't use it to detect when all
images have loaded, it *might* work sometimes.

Here's an old related issue: #34 <https://github.com/haltu/muuri/issues/34>.
Muuri's API has changed from those times though, but the logic is pretty
much the same.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/haltu/muuri/issues/111#issuecomment-345998420>, or mute
the thread

**Comment by niklasramo** [comment]
Depends on this:

> If you use images inside the items and the images affect the items' dimensions...

There are also many cases where an item might look like it's mistakenly overlapping another item if it's content leaks outside the item's boundaries. This has nothing to do with Muuri, it's just CSS. Muuri never modifies items' dimensions, it just reads them.

**Comment by mmikaela** [comment]
Hi everyone, thanks for your help! My images will always be a 1:1 ratio so I'm not sure if my problem is applicable to what dgeorgy007 mentioned, but the code that niklasramo posted worked for me! I know you mentioned it in your first comment, but I'm still learning Javascript/JQuery syntax so I wasn't sure where to put it until you spelled it out more. Thank you again!

**Comment by andimg93** [comment]
> var grid = new Muuri('.grid');
> window.addEventListener('load', function () {
>   grid.refreshItems().layout();
> });

The window load event listening is not fixing the problem, but what it does is using the imagesLoaded functionality of desandro as mentioned by niklasramo - Thank you!
