### ISSUE TITLE
Incompatibility with latest version of Hammer

### ISSUE THREAD

**Issue by lalitindoria** [haltu/muuri#129]
Drag drop with latest version of Hammer - 2.0.8 does not seem to work anymore. Drag events are not fired and no errors on console either.

**Comment by niklasramo** [comment]
Muuri's website and all the [demos here]( uses v2.0.8

**Comment by folkevil** [comment]
i got same problem, used with bootstrap, any conflict ?

> muuri.min.js:29 Uncaught TypeError: Cannot read property 'style' of undefined
    at C (muuri.min.js:29)
    at Object.start (muuri.min.js:29)
    at new r (muuri.min.js:29)
    at muuri.min.js:29
    at Array.forEach (<anonymous>)
    at new n (muuri.min.js:29)
    at HTMLDocument.<anonymous>

**Comment by niklasramo** [comment]
@folkevil could you please provide [reduced test case](https://css-tricks.com/reduced-test-cases/) and put it on codepen/jsfiddle for example? It's the first step before I can start looking in to the issue since it's not reproducing in my own demos and the website. If there really is a bug, would be nice to squash it.

**Comment by niklasramo** [comment]
I'm closing this since I can't reproduce this and no reduced test case has been provided.

**Comment by ubergeoff** [comment]
This seems to happen when there are odd number bound to the grid.

I can patch fix this by doing:

```
if (item._child) {
```

within the _finishMigration function
