### ISSUE TITLE
Kanban board & event emitter on drop

### ISSUE THREAD

**Issue by bcmendoza** [haltu/muuri#131]
Hello! Excellent work on this project!!

I'm currently working on a project that will use a Kanban board. How difficult would it be to setup the same implementation you have on your demo page?

Secondly, I would like to have the Kanban board persist state over sessions. Would it be feasible to this somehow?

**Comment by niklasramo** [comment]
Thanks! 😊 

Well the website's kanban board code is in the repo so it's just a matter of copy and pasting pretty much. But since you're not the first one to ask it, here you go: https://codepen.io/niklasramo/pen/ppeMbK.

As for persisting state, well yes it is possible, but Muuri does not have any built-in helpers for that. Muuri provides you the order of the grid items via [`grid.getItems()`](https://github.com/haltu/muuri#gridgetitems-targets-state-) and allows you to sort the items via [`grid.sort()`](https://github.com/haltu/muuri#gridsort-comparer-options-). The rest of the implementation is up to you. A lot of ways to do it really.

**Comment by bcmendoza** [comment]
Thank you! Much appreciated. I will look into it.
