### ISSUE TITLE
tabindex when rearranged

### ISSUE THREAD

**Issue by abhipanda** [haltu/muuri#138]
Thanks for this awesome library.

When tabbing across cards I noticed the tabindex is not consistent with arrangement of cards. Is it possible to keep cards in consistent with natural tabbbing of the page after rearranging ?

Thanks,
Abhi

**Comment by niklasramo** [comment]
You could use `grid.synchronize()` everytime the layout changes so the DOM elements will be kept in sync with the order of the items. Or just manually manage the [`tabindex`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) attribute for the items (update it after each layout).

Please do note that you will likely face some issues when dealing with tab index when using a gapless layout (`fillGaps` enabled) since the order of the items does not match the _visual_ order of the items. No easy solution for that. But if you think of one please do share  :)

**Comment by abhipanda** [comment]
thanks that works.
