### ISSUE TITLE
[Suggestion] Method to match Muuri internal state to DOM state 

### ISSUE THREAD

**Issue by kieraneglin** [haltu/muuri#146]
I'm writing a library to bridge Muuri and Vue 2.x.  Since Vue is reactive, I'm running into problems when the parent component alters the prop that it's sending to my Muuri component.

As an example, here's some dummy code and a simple explanation of a problem I'm facing:

```html
<div class='v-muuri-grid>
  <div class='v-muuri-item' v-for='item in list'>
    <div class='v-muuri-item-content'>
      {{ item.name }}
    </div>
  </div>
</div>
```
If you're unfamiliar with Vue, this will create one `v-muuri-item` for each element of `list`.  However, since Vue will change the elements of this list reactively, It's very hard to keep Vue and Muuri in sync.

**Scenario:**
1. `list` contains `['a', 'b', 'c']`.  This is passed to Vue, creating a DOM element for each item
2. Using Muuri, I drag item `'c'` to the 0th index
3. Listening to `grid.on('move')`, I then update `list` so its structure matches the DOM structure (`list` is now `['c', 'a', 'b']`)
4. Due to reactivity, this causes a re-render, changing the display names of the items.  _However_, since the Muuri representation of these items doesn't update when the DOM does, the display names become `'a'`, `'b'`, and `'c'` again, leaving `list` out of sync with Muuri.

[Here's a video](https://media.giphy.com/media/xUNd9VeeQTNGweUu5O/giphy.gif
) of this happening.  Notice that the box labels change to the wrong label when the Vue state changes.

___

Now, this one issue isn't hard for me to fix.  But handling the reactivity when an array is added to, deleted from, or replaced is pretty convoluted.

My suggestion is a method that reevaluates Muuri's internal state based on the current DOM.  Kind of like `synchronize`, but in reverse.

Thank you for this great library!

**Comment by niklasramo** [comment]
Hmmm... to me it seems that the reason this happens is that Vue manipulates DOM when Muuri is not expecting it. You can always manipulate Muuri's internal state directly via `grid._items`. It's an array of the item objects and that's the single source of truth for Muuri (regarding the order of items).

It's going to be superhard to make a _good_ wrapper for Muuri for any rendering library (Angular / React / Vue) because Muuri does quite tricky DOM manipulation and has an internal system for batching DOM reads and writes using requestAnimationFrame (to minimize layout thrashing). 

So be warned, it's not going to be easy bridging Muuri to Vue, but I hope for the best ;)

**Comment by kieraneglin** [comment]
Hmm, this is looking trickier than expected!  Thank you for the info
