### ISSUE TITLE
The `remove` event doesn't contain indices

### ISSUE THREAD

**Issue by aslakhellesoy** [haltu/muuri#149]
The [documentation for remove](https://github.com/haltu/muuri/blob/0.5.3/README.md#remove) incorrectly states that `indices` of removed items are passed as an argument. The code passes the removed `items` instead.

I'm writing an application that keeps a data model in sync with a Muuri instance, and this is awkward to implement without knowing the indices of items that have been removed.

I would suggest adding a 2nd event (`removeIndices`) that reports the removed indices (and keeping the current behaviour of `remove`, for backwards compatibility).

**Comment by niklasramo** [comment]
@aslakhellesoy good catch! The documentation is indeed out of sync with the code. I see that you have PR ready for that (+ some additional stuff). Thanks for that too!

I think I have thought about this issue before (looking at the remnant in the docs), but for some reason (probably consistency) have decided to provide the items instead of indices as the argument. Now looking at the code it's indeed a bit tricky, but possible, to get the indices inside the `remove` event. Simplest way is to keep the `grid._items` cached in some variable and update that cache every time the order or amount of the items changes. Then you could just do the following:
```
grid.on('remove', function (items) {
  var indices = items.map(function (item) {
    return itemsCache.indexOf(item);
  });
});
```

However, I wouldn't go as far as to creating a new event specifically for emitting the indices of removed items. Adding the indices as the second argument of the `remove` event would probably be the logical way to go here. That's probably going to happen somewhere down the road and I'll keep this in mind for the next update.

**Comment by niklasramo** [comment]
Thanks @aslakhellesoy for fixing this for us: https://github.com/haltu/muuri/pull/150. The fix will be added to the next release.

**Comment by aslakhellesoy** [comment]
Thanks a lot, and thanks for Muuri - it’s great!

**Comment by niklasramo** [comment]
This is released now -> closing.
