### ISSUE TITLE
% margin and different dragContainer causes item shift on dragInit

### ISSUE THREAD

**Issue by awreccan** [haltu/muuri#156]
Item margin specified in 'px': https://codepen.io/awreccan/pen/POpXMG
Item margin specified in '%': https://codepen.io/awreccan/pen/XEaVMM

The only difference between the two codepens above is that the `.item` margin is specified in `%` vs `px`. 

As you notice, when specified in `%`, the margin value changes when the item is attached to the `dragContainer` element because it is calculated as a % of the `dragContainer`'s width rather than its `grid`'s width.

![image](https://user-images.githubusercontent.com/10543509/37863714-efba7c86-2f9d-11e8-9b27-92c9af8464c7.png)
ref: https://developer.mozilla.org/en-US/docs/Web/CSS/margin

**Comment by niklasramo** [comment]
Yep, this is a known issue. Same issue occurs with percentage width/height. Originally Muuri automatically "freezed" the dragged element's dimensions and margins for the duration of the drag so that this would not happen, but I removed that and instead provided the `dragInit` event, which can be used to do exactly that. The reason I did that change was to give more control to the users over the library's behaviour.

This is how you would freeze the dimensions to pixel values on `dragInit` and unfreeze the dimensions on  `dragReleaseEnd`:

```javascript
grid.on('dragInit', function (item) {
  var elem = item.getElement();
  var margin = item.getMargin();
  elem.style.width = item.getWidth() + 'px';
  elem.style.height = item.getHeight() + 'px';
  elem.style.marginLeft = margin.left + 'px';
  elem.style.marginRight = margin.right + 'px';
  elem.style.marginTop = margin.top + 'px';
  elem.style.marginBottom = margin.bottom + 'px';
})
.on('dragReleaseEnd', function (item) {
  var elem = item.getElement();
  elem.style.width = '';
  elem.style.height = '';
  elem.style.marginLeft = '';
  elem.style.marginRight = '';
  elem.style.marginTop = '';
  elem.style.marginBottom = '';
})
```

**Comment by niklasramo** [comment]
Closing -> known issue with workaround provided.
