### ISSUE TITLE
Just a query that why Muuri is not production ready as we are using this in our product... Do we need to worry about this??

### ISSUE THREAD

**Issue by gurpreetkaurahuja** [haltu/muuri#196]

**Comment by niklasramo** [comment]
Well, I guess it's just a matter of view. How would you define production ready? What checkboxes need to be ticked in order it to be production ready?

**Comment by gurpreetkaurahuja** [comment]
Thank you @niklasramo for instant reply :)

I agree that's difficult thing to say! But, atleast I feel that a most important checkbox for it would be that "As it is being developed and updated frequently, there should not be any possibility of changing it from the core", as this will hamper the production based development.

So can we atleast get clarity on it? That, In future it would not be re-implemented from scratch or core? :)

**Comment by niklasramo** [comment]
There is a high possibility Muuri will be re-implemented from ground up many times over in the future, can't make any guarantees on that. But that's why we have versioning. We'll do our best to follow semver 2 versioning. But... since we haven't yet reached 1.0.0 version there's a good chance that things in the core and public API will still change.

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

So in that sense Muuri is not yet recommended for production. However, Muuri is very stable at the moment and does have plenty of unit tests. Just lock the version tight when you start developing on Muuri and check carefully before updating to new version. Personally I'd use Muuri in production today without a worry.

By the way, to speed up the process of Muuri getting to 1.0.0 version I'd appreciate as much feedback as possible about everything (API, performance, bugs/issues, unit tests, docs etc).
