### ISSUE TITLE
how to apply nth-child marign?

### ISSUE THREAD

**Issue by kkak10** [haltu/muuri#199]
I want to apply margin-right using nth-child.

I wish there were seven items in a row that I am creating and the last item was not a right margin.

So I applied the margin-right of seventh item to 0 using nth-child.

And I drag it and I change its sorting, it doesn't work as intended.

[example](https://codepen.io/kkak10/pen/NBYqRV)

In the example, the width of the .wrap is 600px and the .item is 200px so margin-right is 5px, but I want to draw 3 items per line.

**Comment by niklasramo** [comment]
nth-child is a bit problematic with Muuri, since it's based on the order of items in the DOM, but Muuri positions the items based on the order in the grid._items array. You can use grid.synchronize() method to arrange the DOM nodes based on the items order, but even that's not gonna always help if you have fillGaps activated.

As for the example, which is unrelated to nth-cihild, just give the container width of 615px... or items width of 195px.

**Comment by niklasramo** [comment]
Seems resolved -> closing
