### ISSUE TITLE
Add patreon

### ISSUE THREAD

**Issue by ppwfx** [haltu/muuri#208]
Hey, 

can you add a patreon link?

**Comment by niklasramo** [comment]
I've actually thought about this before, but AFAIK it's quite hazzle to accept Patreon donations/payments here in Finland (there are some legal issues with accepting donations). Unless there's a huge income stream coming in from Patreon it might actually have an adverse effect on Muuri's development (figuring out taxes and legal stuff vs developing Muuri) 😛But I'll definitely look into it.

In any case, very nice to see issues like these ❤️At the moment it's just me and a few occasional contributors developing and maintaining Muuri. And personally I have very limited time to dedicate on Muuri's development at the moment. If there was monetary compensation available I _could_ dedicate a lot more time to Muuri's development which is why I've been lately thinking a lot about different ways to finance Muuri's development.

Here are some things I've been considering:
  - A private support forum/chat (e.g. slack) where you get access with a monthly fee.
  - Some quality Muuri plugins that add some often requested extra features, which likely never get added to the core (e.g. selectable items, resizable items, etc.)
  - A kanban board library based on muuri

What do you guys think, does any of them sound like something you'd pay for?

**Comment by 21stio** [comment]
It's actually pretty simple to accept Patreon contributions. Just add them in your tax statement as additional income. As you aren't a non-profit a payout is basically income and isn't considered a donation.

> Some quality Muuri plugins that add some often requested extra features, which likely never get added to the core (e.g. selectable items, resizable items, etc.)

I'm very much into the idea of raising funds for features. I'd definitely partipate in funding selectable items, resizable items and react support.

**Comment by 21stio** [comment]
Maybe the fundraising could be facilitated by issuehunt.io

**Comment by niklasramo** [comment]
I joined the github sponsors program and you can sponsor me there now: https://github.com/sponsors/niklasramo :slightly_smiling_face:
