### ISSUE TITLE
Allow dropping an item over an empty space

### ISSUE THREAD

**Issue by niklasramo** [haltu/muuri#26]
**Problem**

A dragged item needs to overlap another item in order for moving to happen. A dragged item can not be dropped on empty gaps within the grid, which feels like bug.

**Solution**

When calculating the layout, don't lose the empty slots data, but instead use it for the drag overlap calculations. For example, connect each empty slot to an actual item and when the dragged item overlaps an empty slot the item is moved in place of the slot's connected item. The current layout data should be stored in the `Muuri` instance.

**Comment by Eldair** [comment]
Hello, Is this ready in dev branch?

**Comment by niklasramo** [comment]
Nope, haven't had the time to start working on this one yet.

**Comment by niklasramo** [comment]
Managed to get this one working pretty decently, but not decently enough. Sorting with the gaps did not feel intuitive at all. Also, it needed a lot of code to make this happen and affected negatively on the performance. So I'm dropping this feature from the upcoming v0.3.0 release. Maybe I'll revisit this one for v1.0.0.

**Comment by kirilvit** [comment]
Are there any plans to fix this issue?

**Comment by niklasramo** [comment]
At some point, yes. Help with this one would be much appreciated. Figuring out the logic is the hardest part for this one. I have tried to solve this twice already, but was never happy with end result.

**Comment by niklasramo** [comment]
@ryandegruyter I'm not sure if they are anywhere to be found anymore unfortunately, it was a long time ago when I tried to solve this problem.

**Comment by ryandegruyter** [comment]
Ok thanks, we are looking into this. Will let you know if I come up with any good solution.

**Comment by AndrewBotsulyak** [comment]
@ryandegruyter Have you fixed this problem?

**Comment by aPinix** [comment]
### **Any news on this subject?**
It would be perfect to have empty slots without pushing the ones on the right.

**THIS:**
| Steps | 1 | 2 | 3 | 4 | 5 |
| - | :---: | :---: | :---: | :---: | :---: |
| Step 1 | 🟦 | ⬜️ | ⬜️ | 🟦 | 🟦 |
| Step 2 | 🟦 | ⬜️ | 🟦 | 🟦 | 🟦 |
| Step 3 | 🟦 | ⬜️ | ⬜️ | 🟦 | 🟦 |

**INSTEAD OF THIS:**
| Steps | 1 | 2 | 3 | 4 | 5 | |
| - | :---: | :---: | :---: | :---: | :---: | :---: |
| Step 1 | 🟦 | ⬜️ | ⬜️ | 🟦 | 🟦 | |
| Step 2 | 🟦 | ⬜️ | 🟦 | 🟦 | 🟦 | 🟦 |
| Step 3 | 🟦 | ⬜️ | ⬜️ | 🟦 | 🟦 | |

**Legend:**
⬜️ Empty Slot
🟦 Item

**Comment by brentN5** [comment]
Any updates to this?
