### ISSUE TITLE
Allow grouping & sorting by css classes

### ISSUE THREAD

**Issue by mach37** [haltu/muuri#27]
Hi, first this is wayy better than masonry if you ask me 👍 

Can you please share some guidance on how to do grouping of all blue items and then sort them by a data-element

- In the main demo you have filtering, but the other colors  disappear, I wanted to know - how to group the items by the same colors and so we would have a row of all, blues, greens etc
- The sort would allow us rank by weight etc.

**Comment by niklasramo** [comment]
Hi! Thanks for the feedback and sure I can help you out. Currently Muuri doesn't provide any kind of sorting API, because the items can be sorted easily without any extra methods.

After you have created a Muuri instance, you can access the item instances via `_items` property. It's always an array. You can sort the array with [Array.prototype.sort()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort). And that's  pretty much it. Just sort the `_items` array and call `layout` method.

I have been thinking about introducing some kind API for sorting the items so that users don't have to resort to mutating the internal items array. Maybe I'll build a sorting plugin for Muuri later on that has all the bells and whistles, but I think the core library does not need any extra methods for sorting.

> In the main demo you have filtering, but the other colors disappear, I wanted to know - how to group the items by the same colors and so we would have a row of all, blues, greens etc

In the main demo if you click the select box which has the initial value "Drag" and select "Color (drag disabled)" option, doesn't it do exactly what you want? At least it should sort the items by color. If you want to see how that's done please refer to the source code of the website. Unfortunately I haven't had the time yet to write down detailed usage examples and guides, but I'll get to that soon enough, hopefully =)

**Comment by niklasramo** [comment]
Alrighty, thought this over and came to this conclusion: https://github.com/haltu/muuri/issues/29. Also filtering API will be added: https://github.com/haltu/muuri/issues/28
