### ISSUE TITLE
Recalculate the grid

### ISSUE THREAD

**Issue by upendra-web** [haltu/muuri#271]
I am using Muuri for a masonry card grid, which frequently updates by adding or removing cards.

So, does Muuri has an option to recalculate the grid which includes the newly added card or removal of the card?

**Comment by niklasramo** [comment]
grid.layout(), but that is called qutonatically by default when you gtid.add() or grid.remove() :thinking:

**Comment by upendra-web** [comment]
Sorry for confusing you. I was using Muuri with Vue js. First I render the cards using v-for and then initiated a Muuri instance to create a grid using cards. I am facing problems while removing an element from the list. Can you tell me how to an element from the grid?

**Comment by niklasramo** [comment]
It's all in the docs ;)

**Comment by upendra-web** [comment]
I made a [codepen snippet](https://codepen.io/upendra_m/pen/KYXmaK) to give you a clear understanding of my problem

When I use `removeElements: true` the list I use to render does not update, while if I use remove event to delete the element from the list, something strange happens. Please look into the codepen snippet.

**Comment by niklasramo** [comment]
@upendra-web https://codepen.io/niklasramo/pen/ZZaEJX

The problem in your demo was that the rendered items were not _keyed_: https://vuejs.org/v2/guide/list.html#key

Also, you should put the _visual_ styles of the Muuri items to the `.item-content` (not `.item`) since Muuri animates the inner element when doing `grid.show/grid.hide()`

**Comment by upendra-web** [comment]
Yes, that solved the problem. Thanks for the solution.
