### ISSUE TITLE
CSS 3 dense grid layout?

### ISSUE THREAD

**Issue by msdobrescu** [haltu/muuri#276]
Is there an algorithm close to css 3 grid dense layout?
I see Muuri making gaps, there are some cases when a better placement could be done, avoiding the few gaps (when set for no gaps).
What is the algorithm of dense grid?

**Comment by niklasramo** [comment]
Not sure what's the dense grid's exact algorithm, but it looks very identical to how Muuri's default algorithm works when `fillGaps` is set to `true`: https://github.com/haltu/muuri#layout-

**Comment by msdobrescu** [comment]
Hello, thanks for replying!
This would have been fine, even though it is not the same setup as CSS grid.
Only if it worked...
Even your example has gaps sometimes.
My setup is also simple - I combine squares on 4 columns, some squares are simple sized (1 x 1), some are .... "double" (2 x 2).
There are gaps with fill gaps option enabled.

**Comment by msdobrescu** [comment]
Randomly refresh a few times:
![index](https://user-images.githubusercontent.com/7279637/57276112-3efc0b00-70a9-11e9-9ea8-0e623692351d.png)

**Comment by msdobrescu** [comment]
Randomly refresh, after a few attempts and filtering:
![index](https://user-images.githubusercontent.com/7279637/57276232-9d28ee00-70a9-11e9-93ee-d6b12bdad8f2.png)

**Comment by niklasramo** [comment]
Can you do a live demo that showcases in which scenario grid-auto-flow: dense provides different results than Muuri with fillGaps: true? I'd be curious to find out the differences in the algos.

In any case, yes, there might be gaps in the layout even with muuri's fillGaps. That's because Muuri tries to find the best place for the item without repositioning items that are already positioned when looping through the items.

**Comment by msdobrescu** [comment]
I don't need a identical result, but a grid without gaps, even though some items are repositioned, at least as an option. So CSS grid does. I understand your point too. Still, CSS has a fast solution. I'll try to do a layout of a similar setup as above in CSS, out of curiosity.

**Comment by msdobrescu** [comment]
I see CSS performs the same until grid-template-columns: repeat(auto-fit, minmax(..., 1fr)); is used.
This makes it compact.

**Comment by msdobrescu** [comment]
Hi, I think a better algorithm than CSS's would be great, for cases like this.
I have had the feeling that aggressive reordering was avoided.
Now that you confirm it, I say, would be great to be able to let some more freedom, to be able to disable this rule, in this regard. Would be interesting to see how it performs.
What do you think? I know it's not trivial.

**Comment by niklasramo** [comment]
I think adding that to the core is probably not ideal, it's more code and one option more to maintain. Since Muuri provides an API for providing your own layout algorithm I think that's what should be used in this case. I hope I have time to add some custom layout algorithms to the repo as a demonstration, but we'll see.
