### ISSUE TITLE
How to build own demo?

### ISSUE THREAD

**Issue by PrestaShark** [haltu/muuri#31]
Hi!
Just found Your script from eWebDesign Newsletter Issue #178 👍 
Looks very promissing but forgive my noob question

Where is the content of the grid in demo? :O
i see only <div class="grid"></div> in index.html but on the browser i see filled grid container...
I want to try adapt it into Prestashop bootstrap theme. Masonry/Packery works fine. I will give muuri a chance :)

**Comment by niklasramo** [comment]
Hi! Not a noob question at all :) The items are generated with JavaScript on page load, most of the magic happens in [this function](https://github.com/haltu/muuri/blob/gh-pages/scripts/main.js#L275).

The current state of documentation has a lot of room for improvement, but worry not, there's more demos and usage guides up after I get the v0.3.0 released, which I'm working on currently. A lot of new cool features and improvements coming up very soon ;)

And thanks for giving Muuri a chance, I hope it works out for you. And if it doesn't I'd be interested to hear the issues so I can make it better :)

**Comment by PrestaShark** [comment]
Thanks for clarify!
Huh! Is there any way to build grid without .js function - just by foreach smarty/php loop?

**Comment by sjoerdfaerber** [comment]
Yes I am also curious about this :)

**Comment by niklasramo** [comment]
Have you read the [Getting started](https://github.com/haltu/muuri#getting-started) section in the documentation? There's a step-by-step guide on how to build your demo with minimal configuration. Pasting the code snippets in the tutorial to codepen produces something like this: http://codepen.io/niklasramo/pen/jyJLGM. I tweaked the tutorial code a bit to make it look a bit nicer.

And no, there's no need to dynamically create the items, it was just my preference in the demo site, because I had to anyway create items on the fly when the user clicks the "Add more items" button.

**Comment by niklasramo** [comment]
By the way I just noticed that in the codepen demo the dragged item does not move when the container is scrolled, which is a bug. I suspect it's related to codepen somehow since I can't replicate the issue in my own demos. Gotta check that out.

**Comment by PrestaShark** [comment]
Well done @niklasramo ! 
Thanks for it! :)

**Comment by niklasramo** [comment]
No problem :) Just confirmed that the "dragged item not moving when scrolling container" issue is a valid bug, gonna fix it asap and get it fixed for v0.3.0.
