### ISSUE TITLE
drag images

### ISSUE THREAD

**Issue by YvonneD** [haltu/muuri#34]
I love muuri,but not clear on how to applay to a real project. And I got a question when try it. Why the images concluded in the item-content can not be dragged? Is that OK  to insert different size pictures? How can I  fix my code. Thanks.
[http://codepen.io/diyifang/pen/NdVgNX](url)

**Comment by niklasramo** [comment]
Hi! Glad to hear you're enjoying Muuri :slightly_smiling_face:

>Why the images concluded in the item-content can not be dragged?

If you have images or links inside the items or if the item itself is link or image Muuri's dragging will not work as you might expect. That's because images and links have native browser dragging enabled (try to drag any link or image on this very page and you will see that it will be dragged), which interferes with Muuri's Hammer.js bindings. So to overcome this problem you need to manually prevent the browser's native dragging for images and links within Muuri's items.

Here's a very basic example that will get the job done for images in your demo:
```
// Prevent native image drag for images inside items.
var images = document.querySelectorAll('.item img');
for (var i = 0; i < images.length; i++) {
  images[i].addEventListener('dragstart', function (e) {
    e.preventDefault();
  }, false);
}
```

The upcoming v0.3.0 version of Muuri prevents automatically native link/image drag for the item element and the item content element, but it's up to the user to prevent the drag for any links/images inside the item content element.

>Is that OK to insert different size pictures?

Yes. Any item can be any size. Just remember to call `muuri.refresh()` method whenever any item's dimensions are changed after initiating the Muuri instance. In your demo the images inside the items were not loaded when Muuri was initiated so the items had width and height of `0px` during initiation, which caused all the items to overlap each other when the images were finally loaded. You need to call `muuri.refresh()` and `muuri.layout()` (in that order) after the images have loaded or provide a fixed width and height for the items.

> How can I fix my code.

http://codepen.io/niklasramo/pen/apryKy

**Comment by YvonneD** [comment]
@niklasramo Thanks so much! I'll continue to follow your project. 👍
