### ISSUE TITLE
Disabling drag on mobile prevents page scrolling.

### ISSUE THREAD

**Issue by Likewise42** [haltu/muuri#348]
When you turn dragging off it prevents mobile scrolling. You can see this pretty easily on the muuri grid demo by just disabling dragging. Is there a way to enable scrolling when drag is disabled? Thank you!

edited for grammar because im at a desktop again

**Comment by niklasramo** [comment]
_How_ are you turning dragging off?

**Comment by Likewise42** [comment]
On the Muuri demo located at haltu.github.io/muuri I turned the Drag drop-down to "Title (drag disabled)"
![Screenshot_20191031-155043](https://user-images.githubusercontent.com/10952416/67981155-66660780-fbf6-11e9-89cb-de042f73b786.jpg)

**Comment by Likewise42** [comment]
This is happening on Chrome 78.0.3904.62 / Oxygen OS 9.5.13.GM21AA, and iOS 12.4.2

**Comment by niklasramo** [comment]
Ah, yes. Long story short, if you want to _fully_ disable/enable drag you gotta do this:

```javascript
// Destroy drag for all items.
grid.getItems().forEach(item => {
  if (!item._drag) return;
  item._drag.destroy();
  item._drag = null;
});

// Enable drag for all items.
grid.getItems().forEach(item => {
  if (item._drag) return;
  item._drag = new Muuri.ItemDrag(item);
});
```

Reference: https://github.com/haltu/muuri/blob/master/src/Item/Item.js#L100

I know I know, it's _ugly_ and there should be a better way to handle this. It _should_ be enough to just manually override the CSS `touch-action` value of the item (that's what blocks the scroll), but because not all browsers support all touch-action values Muuri simply prevents default on touchstart if the browser does not support the requested touch-action. You can provide the touch-action property to Muuri here: https://github.com/haltu/muuri#dragcssprops-

**Comment by Fabricio-L** [comment]
Hello, I have the same problem, I can't Scroll on mobile when I disable Drag.
I don't understand how to apply the mentioned solution.
This is the code for the Muuri component options

`const isDragEnabled = window.innerWidth > 768

// Grid static options.
export const options = {
  fillGaps: true,
  layoutOnResize: true,
  dragSortHeuristics: {
    sortInterval: 70,
  },
  layoutDuration: 400,
  dragRelease: {
    duration: 400,
    easing: 'ease-out',
  },
  dragEnabled: isDragEnabled,
  dragContainer: document.body,
  // The placeholder of an item that is being dragged.
  dragPlaceholder: {
    enabled: true,
    createElement: function(item) {
      // The element will have the Css class ".muuri-item-placeholder".
      return item.getElement().cloneNode(true)
    },
  },
  dragStartPredicate: function(item, hammerEvent) {
    if (
      hammerEvent.target.matches('button') ||
      hammerEvent.target.matches('svg')
    ) {
      return false
    }
    if (hammerEvent.target.matches('input')) {
      return false
    }
    if (hammerEvent.target.matches('a')) {
      return false
    }
    if (hammerEvent.target.matches('label')) {
      return false
    }
    if (hammerEvent.target.matches('img')) {
      return false
    }
    // handle Drag
    return true
  },
}`

Please, help!
