### ISSUE TITLE
Create a "fixed bin" grid?

### ISSUE THREAD

**Issue by DouglasUrner** [haltu/muuri#354]
Is it possible to create a grid of say 32 bins in a 4 by 8 array such that fixed size items (all the same size) can be dragged into arbitrary bins in the grid. My use case is to drag items from a list of students into a seating chart.

**Comment by niklasramo** [comment]
The _grid_ is a bin in Muuri's case, but it can contain other bins (grids). So yes, you could nest 32 child grids inside the main grid and  add some logic which prevents adding more than one _item_ inside a child grid. In this scenario you could also make it so that the child grids can be dragged and sorted within the main grid.

This kanban demo is actually working with that logic: https://codepen.io/niklasramo/pen/ppeMbK (except that you can drop n-amount of items within the child grids/bins).

**Comment by DouglasUrner** [comment]
Thank you for pointing out how the kanban demo worked, it gave me the start I needed.
