### ISSUE TITLE
Sorting a grid after adding an item

### ISSUE THREAD

**Issue by DouglasUrner** [haltu/muuri#357]
I'd like to sort the contents of a grid after adding an item to it. My first attempt was to do, roughly:
```javascript
grid.on('layoutStart', function(items) {
  grid.sort('id');
}
```
However that seemed to result in an infinite loop. The item is coming from another grid, so I also tried using the `receive` event hook, but that also failed.

Is it possible to keep a grid sorted as new items are added? What event should I be using?

**Comment by niklasramo** [comment]
Yep, the infinite loop happens because all the grid methods which (potentially) mutate the internal `grid._items` array call `grid.layout()` automatically. So when you call `grid.sort()` within the `layoutStart` event it triggers another layout, and another and so on.

I actually struggled with this logic a lot when thinking about the how the API should work. Should we _always_ require manual `grid.layout()` or should it be automatically called where logical in most cases? In any case I built an escape hatch for that functionality as I knew it would not fit to all situations.

All the methods which do automatic layout `add/remove/show/hide/sort/filter/move/send` also accept a configuration object which allows preventing the automatic layout. In the case of `add` method it would look like this `grid.add(elements, {layout: false});`. So with that in mind, one way to keep the grid always sorted is to never do automatic layout and always call `grid.sort()` after you have e.g. added/removed items.

Another pretty straightforward way would be doing this:

```javascript
grid
.on('add', function() {
  grid.sort('id', { layout: false });
})
.on('remove', function() {
  grid.sort('id', { layout: false });
});
```

This method works nicely because the `add` and `remove` events are emitted just before the automatic layout call, so you can sort the items nicely before the layout happens. It's also important to do the sorting without layout so that we do accidentally do an extra layout.

I hope this helps 👍

**Comment by DouglasUrner** [comment]
As usual, that helps a lot! I **really** appreciate the time and thought that you put into answering questions. Does the `receive` method also do automatic layout? Or, if not, is it easy to explain the thinking behind that?

**Comment by niklasramo** [comment]
There is no receive method, it's an event: https://github.com/haltu/muuri/blob/master/README.md#receive

So no, it does not trigger layout ;)
