### ISSUE TITLE
Sorting error with saved positions

### ISSUE THREAD

**Issue by austinwbest** [haltu/muuri#365]
[Muuri] sort reference items do not match with grid items.

So i have 10 icons on the page (each represents a module or plugin if you will). I sort them, move them, etc and save the layout to localStorage and refresh. All is well and everything loads where i left it.

Now lets say this number 10 becomes 11 between refreshes. Viola the error happens. 

Ideally it would be best if the data is changed, load what is available and anything new appends to the end. 

Initial page load:
plugin 1
plugin 2
plugin 3
plugin 4
plugin 5

Changes are made and now there is a plugin 6 available but plugins 3 & 4 where removed

so when it reloads the data from localStorage,
plugin 1
plugin 2
plugin 3 (missing now so skip it & flag that the order is not the same)
plugin 4 (missing now so skip it & flag that the order is not the same)
plugin 5
plugin 6 (new so add to the end of the list & flag that the order is not the same)

when it is done loading, save the new sort to localStorage if it is flagged as changed.

Maybe there is a way to accomplish this already & if so i am all for giving it a shot. This isn't something that i can put in codepen or whatever because it would require changing the amount of plugins between page loads to trigger but it is pretty simple to recreate.

**Comment by austinwbest** [comment]
Was going to try a different approach

Use
`		sortData: {
			id: function (item, element) {
				return parseFloat(element.getAttribute('data-id'));
			}
		}	`

To sort

`<div style="float:left;">
    <div class="grid-pluginGrid" style="width:150px;">
        <div class="item" data-id="1">
            <div class="item-content">1</div>
        </div>
        <div class="item" data-id="2">
            <div class="item-content">2</div>
        </div>
        <div class="item" data-id="3">
            <div class="item-content">3</div>
        </div>
        <div class="item" data-id="7">
            <div class="item-content">4</div>
        </div>
        <div class="item" data-id="5">
            <div class="item-content">5</div>
        </div>
        <div class="item" data-id="6">
            <div class="item-content">6</div>
        </div>
    </div>
</div>`

However they still show up 1-6 even though 4 is actually data-id:7 so that method doesn't work either? I would expect 4 to be at the end. I tried `layoutOnInit` both true & false with loading after the call to see if that makes a difference and it doesnt. Again, i guess i am missing something as this seems pretty straight forward so i am sure it is on my code to be the issue

**Comment by niklasramo** [comment]
@austinwbest first of all, I do understand your pain with these issues, it's not as straightforward as it seems at first. The `[Muuri] sort reference items do not match with grid items.` error you are facing is for your protection (although I've actually removed it from the `dev` branch due to performance reasons) because it indicates that you are trying to do something that would cause either a memory leak or data corruption. The method is called `sort` for a reason, there should be only sorting happening 😉 and nothing else. As long as you always provide the existing items (in any order you want) to the sort methods in an array it will work as advertised.

And as for the issue with `sortData` option did you actually call sort `grid.sort('id')`? If you didn't that would be the case.
