### ISSUE TITLE
Vue integration

### ISSUE THREAD

**Issue by pbrzosko** [haltu/muuri#394]
Hi,

first I really like your library :)  It seems to do its job very well.

I am trying to integrate it with Vue in my project. I created two components - Grid and GridItem. GridItem is just a wrapper that add .item class. Grid, on the other hand, holds the state, which is the muuri grid with .item items. But now I have a problem, with how to manage the state of the items in the grid.

I have a dashboard with widgets, more or less looks like that:
`<muuri-grid>
      <muuri-grid-item v-for="(widget, index) in dashboard.config">
        <component :is="widget.component"/>
      </muuri-grid-item>
    </muuri-grid>`

And what I wanted to do at the beginning, is to react on move event and modify the order of the widgets accordingly in the model. But then I noticed, that it breaks the grid, because order of the items in muuri is not changed. So it was reverting the move back...

So I have added an index to the widget. And this is rendered with data- attribute on DOM element. Whenever item is moved, I checked current index with original and update it in the widget if needed and save in database. This way whenever dashboard is rerendered, everything is fine because grid is sorted over this index.

And now I started to implement remove mechanism. And weird things are happening, simply because I remove and item from the grid, but also from the state - list of widgets. And this causes. two widgets to be removed, probably because DOM is changed between those two actions.

So my question is how it should be implemented properly?
Best I would like to manage the state in Vue component, so moving widgets around and deleting in an Array. But somehow synchronized this array with the muuri grid. Is that possible?

My next idea was to recreate the grid everytime the DOM is changed in the component. But I would better go with some kind of synchronization approach.

**Comment by sploders101** [comment]
When trying to implement Muuri into my project, I too had issues with the `<grid><child/><child/>...</grid>` way of doing things. I eventually settled on keeping everything in one component. Vue is meant to be data-driven, so why not have the data drive the grid? Try reading in-depth on slots (namely slot scopes). They *can* be duplicated, and data can be passed to the individual instances: `<div class="item"><slot v-for="n in 4" :number="n"/></div>`. That way, you can have an array of the data you want displayed in your grid, and manipulate that instead of trying to work through numerous layers of refs, DOM elements, etc. I store the key as an attribute on the DOM element so I can go back and match them up later, which helps with sorting the muuri items to match the data, etc. I am unfortunately not allowed to disclose the code that I've used, but my suggestion would be to re-orient the way you think about it from components to data, and focus on keeping them in sync. Muuri's sort function works like an array's, so you can sort the elements, ordering them to match the data based on an HTML attribute that matches a key property in your data. This can also be used for additions and removals via something like `grid.getItems().map((item) => item.getElement().getAttribute("muurikey"))`. Another thing to look out for is when you add or delete, it's a good idea to understand Vue ticks, because the element doesn't get removed as soon as the data does; only on the next tick. Hence, you can tell muuri to remove the element from the grid without deleting it, leaving that responsibility to Vue. I hope this points you in the right direction, and doesn't just create more confusion.

**Comment by pbrzosko** [comment]
Hi,

actually I was able to do it with providing a ref to every item with unique id. Then I am just calling Muuri.add or Muuri.remove with this ref to DOM element, whenever widget is added or removed. When adding I need to do it in Vue.nextTick. Surprisingly, changing order works without problem after this change, but I didn't have time to figure out why. I mean I am reacting to move event and just change the order in Vue model array, and everything works :)
I will close this issue then.

**Comment by niklasramo** [comment]
@pbrzosko The sorting (probably) _just works_ because for Muuri it does not make a difference in which order the item elements are in the DOM. E.g. if you change the order of the DOM elements Muuri's layout will not be affected in any way.

So when you change the item order in Vue model array (on Muuri's move event) Vue will then sort the item elements in the DOM. But as this does not affect Muuri at all, there's no extra work needed here. The only problem I see is that it might take a toll on performance when there are hundreds of items since swapping elements around in the DOM takes some time, it's kind of extra work for no gain (at least in most cases).

**Comment by pbrzosko** [comment]
@niklasramo I just thought totally opposite. My first implementation was to move items around in the model, and what happened with Muuri then was that the item that I grabbed, once I started movement, was replaced with the item I was going to move over. Maybe, it was a mistake in my implementation, maybe some changes I did to Vue (like adding ref to DOM elements) fixed it. And then I thought that it is crucial for Muuri that the DOM order remains unchanged, but apparently this is not the case. I will try to figure this out what changed the behavior in some free time.
Regarding changing the order - I have to store the order in the database. I don't think I will have a lot of items there and I also think that Vue updates the DOM with diff patches, so it shouldn't be a problem. If it will be, I will simply save the order as an attribute of the items instead of moving them around. Thank you for your input and help.

**Comment by sploders101** [comment]
@pbrzosko I also encountered the issue of elements being thrust back into the grid while I was moving them as well. My issue was with the keys. If an item in an array is moved; even if it is an object that has been re-created entirely (`{} !== {}`), Vue will treat them as the same, and re-use the DOM element, as long as the `:key` value is the same. If it is not, the element is re-created, the old one is deleted, and muuri no longer has access to the old element. I've pulled the parts dealing with muuri out into their own file.

Hopefully this helps: https://gist.github.com/sploders101/e80c244310e1e7d8b996f7a98faee9be
It's written in class-based syntax for typescript, but it should be easy to translate if you so choose. This handles keeping Vue and Muuri in sync automatically, as well as adding and removing elements. The default slot uses slot scope to pass the array element to the Muuri item, and once you have that, you can render it however you like.
