### ISSUE TITLE
Get item that's being dragged over

### ISSUE THREAD

**Issue by bernhardberger** [haltu/muuri#408]
How do I get the item that's currently being dragged over (in realtime, beforeReceive hook or similar is too late, I need to know the item that's currently being hovered and would be swapped if I would let go of the drag in realtime)?

**Comment by niklasramo** [comment]
That's a bit complicated to do. You have to compute it manually by comparing the dragged item's position and dimensions to the other items' position and dimensions. The default dragSortPredicate logic does indeed compute this, but it's not advisable to do it on every move as it's a bit heavy operation (the more items there are to compare against the longer it takes to compute the result). That's why there's `sortInterval` options here: https://github.com/haltu/muuri#grid-option-dragsortheuristics.

If you want to go for it you need to do the collision checking in `dragMove` and `dragScroll` events.

**Comment by bernhardberger** [comment]
Thank you. I only have a small number of grids with less than 20 items in any of them. Performance wise I'll be fine, thanks for the heads up though!
