### ISSUE TITLE
Option to use css top/left to position elements instead of translateX/Y

### ISSUE THREAD

**Issue by coffeebite** [haltu/muuri#42]
From a performance perspective, translateX and Y are better, but adding transforms to elements wreaks havoc on the stacking order.

**Comment by niklasramo** [comment]
I wouldn't call it havoc =) But yep, translateX/Y do indeed affect the stacking order. The change you are proposing is totally doable (although it would require a lot of refactoring) but I'm a bit concerned about the actual use cases. Can you provide one or more example scenarios where this kind of option would make sense?

I'd imagine that in most cases the user (developer) can adjust the rest of the styles on the page to overcome the stacking order issues although it might sometimes require a bit more extra work. However, if the left/top properties would be animated instead of translateX/Y properties the animations would not be so smooth and there's pretty much nothing the user could do about that as far as I know.

And if you're wondering why Muuri uses translateX/Y instead of translate3d it's because we still support IE9, at least for now.
