### ISSUE TITLE
How to dynamically add grid sub elements?

### ISSUE THREAD

**Issue by kkueo123456** [haltu/muuri#443]
my grid is v-for an Array,How can I add elements to the array and add one more grid to the page？

**Comment by niklasramo** [comment]
@kkueo123456  I suppose you are using Muuri with Vue? If you are using some Vue specific wrapper library please ask the question in the wrapper library's issues. If not, please provide at least a reduced test case of your code (e.g. in [codepen](https://codepen.io/your-work) or [codesandbox](https://codesandbox.io/)) so that it is easy to debug for anyone who is willing/able to help you out :)
