### ISSUE TITLE
Two Suggestions

### ISSUE THREAD

**Issue by HybridSolutions** [haltu/muuri#49]
Have to say, it looks very promising! Would be interesting to see a selected event for the items. Also, being tied to hammer, not providing your own touch and drag engine is in my opinion, a downside.

**Comment by niklasramo** [comment]
Great suggestions! I've actually been playing with the idea that Muuri would be completely dependency free, but it's not easy to accomplish since Hammer and Velocity are both pretty solid libraries. But on the other hand, Muuri only uses a handful of features from each library so it would make sense to build the animations and dragging into Muuri's core and allow the user to overwrite the built-in animation engine and drag handling with, for example, Velocity and Hammer.

Selected event? What do you mean by that exactly?

**Comment by HybridSolutions** [comment]
Dependency free is the way to go :) There are a lot of developers that might use jQuery UI, Draggabilly or even Rubaxa Sortable, so making them adopt yet another library just for dragging, it's not the ideal solution. As for selecting, I mean an item to be able to fire an event when it gets selected by the user. Also, it would be great to be able to get all the selected items by using a getSelectedItems() function.

Visually, it would allow this kind of things (when in some kind of "edit mode"): 
http://ashobiz.dreamhosters.com/wrapbootstrap/boot-extended18/ui/ui-27.html

I'm leaving you also a couple of links that might get you inspired :)

Gridstack
https://github.com/troolee/gridstack.js

Gridly
http://ksylvest.github.io/jquery-gridly/

What do you think?

**Comment by niklasramo** [comment]
I think selecting the items is outside Muuri's scope, because it's so simple to implement by yourself. Putting the boilerplate inside Muuri would only bloat the core in my opinion.

But yeah, adding a custom drag system in Muuri's core is something I might do somewhere down the road.

**Comment by niklasramo** [comment]
And thanks for the links! I've seen gridstack before, but jquery-gridly was new to me. Actually implementing item resizing should be pretty easy with Muuri also. You only need to implement the item resizing part (use an existing library or roll your own) yourself and the just call the `grid.refreshItems().layout()` when you are done.
