### ISSUE TITLE
Problem Using Percentage Width Items

### ISSUE THREAD

**Issue by who519** [haltu/muuri#53]
Is it possible to use percentages instead of hard coded dimensions for items? I developed my project using them which worked fine on my local, but when I pushed them to my dev site the images weren't loading in time for muuri so leaving my heights at auto borked my grid. Can I use the refresh items function to resize after load? I tried preloading the images, but that hasn't solved the problem. Maybe delay the layout function? If I do delay or refresh...would I put that in the init code or run a separate script? Any help would be greatly appreciated. See my page here... http://www.tomwattsart.com/work.html 

Thanks, 
Tom

**Comment by niklasramo** [comment]
All you need to do is call `grid.layoutItems().layout ();` whenever the size of the items might have changed after the initiation. By default Muuri calls that on window resize. Let me know if that does not work.

**Comment by niklasramo** [comment]
If you know the specific item which's dimensions have changed you can optimize the refreshItems method call by targeting the changed item(s): `grid.refreshItems(elem).layout();`

**Comment by who519** [comment]
my issues is that on load they aren't fully baked so muuri makes the grid with shallow items, should I just call the item refresh onload? Or just write the refresh script just below the init call in a separate script tag?

**Comment by who519** [comment]
I think muuri is looking for the height dimension on load ans reading them as zero, because the height is set to auto in my styles to accommodate for the percentage based width of my items and the images within them haven't loaded yet.

**Comment by who519** [comment]
I did notice that if I resize the page it sets everything correctly.

**Comment by niklasramo** [comment]
Yep, Muuri caches the item sizes on init so you need to refresh the cached dimensions when the items' dimensions change. This very same issue has been discussed here: https://github.com/haltu/muuri/issues/34. Although, keep in mind that Muuri was v0.2.0 version at that time so the example won't work fully with v0.3.0.

For your specific scenario you need to do this:
```javascript
// Refresh item dimensions and do layout after all images have loaded.
window.addEventListener('load', function () {
  grid.refreshItems().layout();
});
```

By the way, you have set CSS transitions to the Muuri item elements on your site which is a big no no and causes very janky animations since it interferes with Velocity's animations. Please read this: https://github.com/haltu/muuri#5-add-the-styles

**Comment by who519** [comment]
Awesome, thanks so much for the advice Niklas, I will get that stuff sorted. I was definitely banging my head against the wall on this one. I really appreciate you taking the time to help out a JS nooby, this tool is awesome. 

cheers, 
Tom
