### ISSUE TITLE
A Few Issues / Ideas

### ISSUE THREAD

**Issue by argie09** [haltu/muuri#56]
Hi! Thanks for an awesome lib!

While testing Muuri out I came across a few issues / ideas:

**Click event propagation in different browsers**
- I need to have links in the grid Items that behave like regular hyperlinks
- in Firefox the click events get propagated normally so you get to open a link with a single click as expected by convention
- in Chrome a drag event is propagated instead of a click event, so a double click has to be used to open a link
- in Chrome sometimes even the double click doesn't work

_Question_: how to harmonize the click event propagation across the different browsers?

**Automatic layout adjustment for dynamically resized items**
- it would be handy if the grid layout would adjust to dynamically resized items by default or it could be an option
- this can now be implemented via event handlers, though

**The performance optimization of the dynamic adding of a batch of items to the grid**
- currently the grid is very efficiently populated with hundreds of DOM items at initiation
- additional items need to be added one by one via grid.add method which seems to be very costly

_Suggestion:_ add a grid.add(array) method that is optimized for speed, e.g. doesn't adjust the layout in between adding items

**Kanban demo board column height equalization**
- in order to handle a lot of items in the Kanban table, the height of all the board columns (.board-column-content) need to be equal to the height of the column with the most items, in order to prevent the need for vertical scrolling while dragging items situated at the bottom of a column to the next column

_Question:_ in your opinion, what would be the optimal technique to accomplish the board column height equalization?

**Comment by niklasramo** [comment]
Hi! First of all a big thank you for the feedback :+1: Much appreciated.

> **Click event propagation in different browsers**

Generally speaking links inside draggable elements are always a bit problematic, but they *can* work together with a little tinkering. Muuri's solution to this issue is the [dragStartPredicate](https://github.com/haltu/muuri#dragstartpredicate-) option. Basically it allows you to control when the dragging should start and, for example, when to follow up on a link if that's what you wish to do. The [default predicate](https://github.com/haltu/muuri/blob/master/muuri.js#L3453) is smart enough to recognize if the item element itself is a link and if so it tries to guess when the user intended to click the item and when the user tried to drag the item. However, if you have links inside the item element you're going to have to get your hands dirty and drop in your own "algorithm" for detecting when to a link was clicked. So the solution here is to build your own dragStartPredicate function (just check out the [default predicate](https://github.com/haltu/muuri#dragstartpredicate-) for reference).

> **Automatic layout adjustment for dynamically resized items**

If I understand you correctly, you mean that Muuri should somehow recognize automatically if the dimensions of an item change. Sounds nice for sure, but I think that's better left outside Muuri's core. There seems to be some libraries that can detect when element's dimensions change (https://stackoverflow.com/questions/172821/detecting-when-a-divs-height-changes-using-jquery). So you only would need to use one of those and then just call `grid.refreshItems().layout()` when the dimensions change.

> **The performance optimization of the dynamic adding of a batch of items to the grid**

Your wish is granted :sparkles: Check out the docs for [grid.add()](https://github.com/haltu/muuri#gridadd-elements-options-). The `.add()` method already accepts an array of elements and adds them to the DOM very efficiently. And yes, you *can* skip the automatic layout after the method is called: `grid.add([elemA, elemB], {layout: false});`

> **Kanban demo board column height equalization**

For your scenario it sounds like setting `min-height` (based on the tallest column) to each column should do the trick. However, if you want to have scrollable columns then things will get a bit trickier mainly because you probably want to scroll the columns while dragging an item. And that's a bit tricky, but doable. Adding that feature to the core is on the roadmap though: https://github.com/haltu/muuri/issues/9.

**Comment by argie09** [comment]
Thank you for the quick comments, they were extremely helpful!

Yet another question came to mind: is it currently possible to "freeze" and "unfreeze" a grid in such a manner that its contents are not manipulatable by a user during a "freeze" state, yet preserving the layout and allowing a full programmatic manipulation access during the state? I need to be able to add and sort items in a grid programmatically while denying a user from messing around with the elements for a periods of time.

**Comment by niklasramo** [comment]
If you mean just disabling the dragging feature temporarily that can be accomplished easily with the [dragStartPredicate ](https://github.com/haltu/muuri#dragstartpredicate-) option. You can check how the demo page does it here: https://github.com/haltu/muuri/blob/gh-pages/scripts/demo-grid.js#L77.

To "freeze" the method calls temporarily just wrap them in your own functions that check if the UI is "frozen" before calling the actual Muuri method.

```
var grid = new Muuri('.grid');
var isFrozen = true;
function add(elems) {
  !isFrozen && grid.add(elems);  
}
```

So, yep, it's possible to "freeze" the grid with a bit of little tinkering.

**Comment by argie09** [comment]
Thank you for the help!
