### ISSUE TITLE
The event dragEnd is triggered when the element still stays in container

### ISSUE THREAD

**Issue by luishdez** [haltu/muuri#86]
I'm trying to use this event to count when there is no children in the container and clean blank spaces in order to be able to use `:empty` selector easily. But when I try to count the children the last item is still there.

If I use Release end the event is triggered from another container. 

Do we've any event that is triggered after the element is really transfer ?

Not sure if I'm missing something.

Thanks!

I see that here the event is emit https://github.com/haltu/muuri/blob/master/muuri.js#L4258 but before the migrating process

**Comment by niklasramo** [comment]
If you drag an item from a grid to another you can use [dragReleaseEnd](https://github.com/haltu/muuri#dragreleaseend) event. If you use the [send](https://github.com/haltu/muuri#gridsend-item-grid-position-options-) method to send item from a container to another you can just use [layoutEnd](https://github.com/haltu/muuri#layoutend) event.

**Comment by niklasramo** [comment]
Getting the events right has been one of the hardest things when designing the API and I'm sure there are still some inconsistencies I'm now aware of. It's a good thing that I get some feedback and questions related to them =) Keep it coming!

**Comment by luishdez** [comment]
My solution was tu use dragReleaseEnd but it's trigged by the container that is receiving the item, not the one that it's getting empty. Same with layoutEnd I can't find the way to access the initial container… 

I've to get all the containers and check all of them Eg.

```js
    muuri.on('dragReleaseEnd', function (item, event) {
      $allContainers.each(function() {
        if($(this).children().length === 0) {
          $(this).text(''); // to clean spaces 
        }
      });
    });
```

**Comment by niklasramo** [comment]
Your solution seems to be working alright for this scenario :+1: There are already `send`, `beforeSend`, `receive`, `beforeReceive` events which can be used to detect when an item is moved between grids and those events have enough data already in my opinion. However, they won't solve your problem since you want to know when the change happens in the DOM.

I gotta put my thinking cap on and revisit the events sometime in the future. Maybe there are some improvements to be made. I'll keep this scenario in mind. Thanks for sharing your issue :slightly_smiling_face:
