### ISSUE TITLE
How create a multiline text in Item?

### ISSUE THREAD

**Issue by tumikosha** [haltu/muuri#94]
How to create a multiline text in Item? How to add button in Item-content? :0((

**Comment by niklasramo** [comment]
Well, by default Muuri itself does not add any styles to the item elements that would prevent text being multiline. I suppose the problem you're having with the button is that the click is not going through because dragging starts or something like that? If so, take a look at [dragStartPredicate](https://github.com/haltu/muuri/blob/master/README.md#dragstartpredicate-). With it you can fully control the drag start logic and allow cli k going through for example.
